# Constants to export and use in util
NATIONS = {
    "Austria": "AT",
    "Belgium": "BE",
    "Bulgaria": "BG",
    "Croatia": "HR",
    "Cyprus": "CY",
    "Czechia": "CZ",
    "Denmark": "DK",
    "Estonia": "EE",
    "Finland": "FI",
    "France": "FR",
    "Germany": "DE",
    "Greece": "GR",
    "Hungary": "HU",
    "Iceland": "IS",
    "Ireland": "IE",
    "Italy": "IT",
    "Latvia": "LV",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Malta": "MT",
    "Monaco": "MC",
    "Netherlands": "NL",
    "Norway": "NO",
    "Poland": "PL",
    "Portugal": "PT",
    "Romania": "RO",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Spain": "ES",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Turkey": "TR"
}

# Nation Zones
ZONES = {
    "Ireland": {
        "Carlow": "CW",
        "Cavan": "CN",
        "Clare": "CE",
        "Cork": "CO",
        "Donegal": "DL",
        "Dublin": "D",
        "Galway": "G",
        "Kerry": "KY",
        "Kildare": "KE",
        "Kilkenny": "KK",
        "Laois": "LS",
        "Leitrim": "LM",
        "Limerik": "LK",
        "Longford": "LD",
        "Louth": "LH",
        "Mayo": "MO",
        "Meath": "MH",
        "Monaghan": "MN",
        "Offaly": "OY",
        "Roscommon": "RN",
        "Sligo": "SO",
        "Tipperary": "TA",
        "Waterford": "WD",
        "Westmeath": "WH",
        "Wexford": "WX",
        "Wicklow": "WW"
    },
    "Italy": {
        "Agrigento": "AG",
        "Alessandria": "AL",
        "Ancona": "AN",
        "Aosta": "AO",
        "Arezzo": "AR",
        "Ascoli Piceno": "AP",
        "Asti": "AT",
        "Avellino": "AV",
        "Bari": "BA",
        "Barletta-Andria-Trani": "BT",
        "Belluno": "BL",
        "Benevento": "BN",
        "Bergamo": "BG",
        "Biella": "BI",
        "Bologna": "BO",
        "Bolzano": "BZ",
        "Brescia": "BS",
        "Brindisi": "BR",
        "Cagliari": "CA",
        "Caltanissetta": "CL",
        "Campobasso": "CB",
        "Carbonia-Iglesias": "CI",
        "Caserta": "CE",
        "Catania": "CT",
        "Catanzaro": "CZ",
        "Chieti": "CH",
        "Como": "CO",
        "Cosenza": "CS",
        "Cremona": "CR",
        "Crotone": "KR",
        "Cuneo": "CN",
        "Enna": "EN",
        "Fermo": "FM",
        "Ferrara": "FE",
        "Firenze": "FI",
        "Foggia": "FG",
        "Forlì-Cesena": "FC",
        "Frosinone": "FR",
        "Genova": "GE",
        "Gorizia": "GO",
        "Grosseto": "GR",
        "Imperia": "IM",
        "Isernia": "IS",
        "La Spezia": "SP",
        "L'Aquila": "AQ",
        "Latina": "LT",
        "Lecce": "LE",
        "Lecco": "LC",
        "Livorno": "LI",
        "Lodi": "LO",
        "Lucca": "LU",
        "Macerata": "MC",
        "Mantova": "MN",
        "Massa-Carrara": "MS",
        "Matera": "MT",
        "Medio Campidano": "VS",
        "Messina": "ME",
        "Milano": "MI",
        "Modena": "MO",
        "Monza E Brianza": "MB",
        "Napoli": "NA",
        "Novara": "NO",
        "Nuoro": "NU",
        "Ogliastra": "OG",
        "Olbia-Tempio": "OT",
        "Oristano": "OR",
        "Padova": "PD",
        "Palermo": "PA",
        "Parma": "PR",
        "Pavia": "PV",
        "Perugia": "PG",
        "Pesaro E Urbino": "PU",
        "Pescara": "PE",
        "Piacenza": "PC",
        "Pisa": "PI",
        "Pistoia": "PT",
        "Pordenone": "PN",
        "Potenza": "PZ",
        "Prato": "PO",
        "Ragusa": "RG",
        "Ravenna": "RA",
        "Reggio Calabria": "RC",
        "Reggio Emilia": "RE",
        "Rieti": "RI",
        "Rimini": "RN",
        "Roma": "RM",
        "Rovigo": "RO",
        "Salerno": "SA",
        "Sassari": "SS",
        "Savona": "SV",
        "Siena": "SI",
        "Siracusa": "SR",
        "Sondrio": "SO",
        "Taranto": "TA",
        "Teramo": "TE",
        "Terni": "TR",
        "Torino": "TO",
        "Trapani": "TP",
        "Trento": "TN",
        "Treviso": "TV",
        "Trieste": "TS",
        "Udine": "UD",
        "Varese": "VA",
        "Venezia": "VE",
        "Verbano-Cusio-Ossola": "VB",
        "Vercelli": "VC",
        "Verona": "VR",
        "Vibo Valentia": "VV",
        "Vicenza": "VI",
        "Viterbo": "VT"
    },
    "Portugal": {
        "Azores": "PT-20",
        "Aveiro": "PT-01",
        "Beja": "PT-02",
        "Braga": "PT-03",
        "Bragança": "PT-04",
        "Castelo Branco": "PT-05",
        "Coimbra": "PT-06",
        "Évora": "PT-07",
        "Faro": "PT-08",
        "Guarda": "PT-09",
        "Leiria": "PT-10",
        "Lisbon": "PT-11",
        "Madeira": "PT-30",
        "Portalegre": "PT-12",
        "Porto": "PT-13",
        "Santarém": "PT-14",
        "Setúbal": "PT-15",
        "Viana do Castelo": "PT-16",
        "Vila Real": "PT-17",
        "Viseu": "PT-18"
    },
    "Romania": {
        "Alba": "AB",
        "Arad": "AR",
        "Argeș": "AG",
        "Bacău": "BC",
        "Bihor": "BH",
        "Bistrița-Năsăud": "BN",
        "Botoșani": "BT",
        "Brăila": "BR",
        "Brașov": "BV",
        "București": "B",
        "Buzău": "BZ",
        "Călărași": "CL",
        "Caraș-Severin": "CS",
        "Cluj": "CJ",
        "Constanța": "CT",
        "Covasna": "CV",
        "Dâmbovița": "DB",
        "Dolj": "DJ",
        "Galați": "GL",
        "Giurgiu": "GR",
        "Gorj": "GJ",
        "Harghita": "HR",
        "Hunedoara": "HD",
        "Ialomița": "IL",
        "Iași": "IS",
        "Ilfov": "IF",
        "Maramureș": "MM",
        "Mehedinți": "MH",
        "Mureș": "MS",
        "Neamț": "NT",
        "Olt": "OT",
        "Prahova": "PH",
        "Sălaj": "SJ",
        "Satu Mare": "SM",
        "Sibiu": "SB",
        "Suceava": "SV",
        "Teleorman": "TR",
        "Timiș": "TM",
        "Tulcea": "TL",
        "Vâlcea": "VL"
    },
    "Spain": {
        "A Coruña": "C",
        "Álava": "VI",
        "Albacete": "AB",
        "Alicante": "A",
        "Almería": "AL",
        "Asturias": "O",
        "Ávila": "AV",
        "Badajoz": "BA",
        "Barcelona": "B",
        "Burgos": "BU",
        "Cáceres": "CC",
        "Cádiz": "CA",
        "Cantabria": "S",
        "Castellón": "CS",
        "Ciudad Real": "CR",
        "Córdoba": "CO",
        "Cuenca": "CU",
        "Gerona": "GI",
        "Granada": "GR",
        "Guadalajara": "GU",
        "Guipúzcoa": "SS",
        "Huelva": "H",
        "Huesca": "HU",
        "Islas Balears": "PM",
        "Jaén": "J",
        "La Coruña": "C",
        "La Rioja": "LO",
        "Las Palmas": "GC",
        "León": "LE",
        "Lérida": "L",
        "Lugo": "LU",
        "Madrid": "M",
        "Málaga": "MA",
        "Murcia": "MU",
        "Navarra": "NA",
        "Orense": "OR",
        "Palencia": "P",
        "Pontevedra": "PO",
        "Salamanca": "SA",
        "Santa Cruz de Tenerife": "TF",
        "Segovia": "SG",
        "Sevilla": "SE",
        "Soria": "SO",
        "Tarragona": "T",
        "Teruel": "TE",
        "Toledo": "TO",
        "Valencia": "V",
        "Valladolid": "VA",
        "Vizcaya": "BI",
        "Zamora": "ZA",
        "Zaragoza": "Z"
    }
}
